baseurl = "/"
languageCode = "en-us"
pygmentsuseclasses = false
pygmentsstyle = "manni"
enableRobotsTXT = true
enableEmoji = true
title = "Netlify Engineering Blog"
author = "Netlify"
disqusshortname = "netlify"
copyright = "Netlify All rights reserved."

[params]
  description = "An Engineering blog for Netlify"
  logo      = "/images/logo-transparent-square.png"
  twitter   = "https://twitter.com/netlify"
  github    = "https://github.com/netlify"
  email     = "help@netlify.com"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"
