baseurl = "/"
languageCode = "en-us"
title = "Netlify Engineering Blog"
author = "Netlify"
copyright = "Netlify All rights reserved."

[params]
  logo      = "/img/logo.svg"
  twitter   = "https://twitter.com/netlify"
  github    = "https://github.com/netlify"
  email     = "help@netlify.com"
